### ISSUE TITLE
修复了若干bug,以及建议

### ISSUE THREAD

**Issue by zeromake** [hilongjw/vue-dragging#6]
## BUG
- [x] vue2 直接更新 list 时 item 对象无法同步 [commit](https://github.com/zeromake/vue-dragging/commit/73c15aa8164cee83db9e6eb15e75d8dbaa430a69) 
- [x] firefox 有 text 元素会报 el.getAttribute is undefined, el.classList is undefined [commit](https://github.com/zeromake/vue-dragging/commit/9209d2be88f282157cc767c58f050cf968650b24)
- [x] 使用相同数据替换 list ，list 数据对象无法同步 [commit](https://github.com/zeromake/vue-dragging/commit/73c3109ac53fbef4c2ef7a0dcf328e9518426a4b)
- [x] 如果一个页面有多个组然后发生两个不同组的 item 拖拽会报错。解决方案见下面的 Current 对象加入group识别。

## 建议
- [x] 添加 dragend 事件回调用于排序的请求触发(后面才改名为dragend) [commit](https://github.com/zeromake/vue-dragging/commit/e744285be8bb2d76323631c93117ae9d5d9c6c22)
- [x] 使用 key 替代 dom 元素，去除 es6 的 Map 依赖 [commit](https://github.com/zeromake/vue-dragging/commit/1f044dbb5b72c2af5e3952a634d1fab2114f1bf8)
- [x] Current 对象无需每个 group 单独使用，事件回调带上group参数，事件绑定解绑优化 [commit](https://github.com/zeromake/vue-dragging/commit/26a08b5a1e821175ee8ae9f7e8338a42ffef061e)

请作者查看后需要哪些我再考虑pr

**Comment by hilongjw** [comment]
@zeromake 感谢，解决了很多问题，我仔细查看之后给你及时回复

**Comment by zeromake** [comment]
@hilongjw 没事慢慢来，我这边工作上用了这个然后发现了这些BUG，现在项目先用npm i github:zeromake/vue-dragging了

**Comment by hilongjw** [comment]
@zeromake 我一一看了，没有什么问题，去除 es6 的 Map 依赖省下不少es6map polyfill 代码量，欢迎发送pull request。

**Comment by zeromake** [comment]
@hilongjw 好的我还是把webpack去掉吧原来直接用rollup转换没有打包es6-map无法直接引入html中使用。现在去掉es6-map的话生成的es5文件可以直接引入js使用使用了。
